-- MySQL Script generated by MySQL Workbench
-- жм 21 янв 2022 19:04:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dz-3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dz-3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dz-3` ;
USE `dz-3` ;

-- -----------------------------------------------------
-- Table `dz-3`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-3`.`student` (
  `id_student` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_student`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz-3`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-3`.`group` (
  `id_group` INT NOT NULL AUTO_INCREMENT,
  `name_of_gropu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_group`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz-3`.`student_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-3`.`student_group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  `time_start` DATE NOT NULL,
  `time_finish` DATE NOT NULL,
  `group_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_student_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_group_idx` (`group_id` ASC) VISIBLE,
  CONSTRAINT `fk_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `dz-3`.`student` (`id_student`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_group`
    FOREIGN KEY (`group_id`)
    REFERENCES `dz-3`.`group` (`id_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz-3`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-3`.`lesson` (
  `id_lesson` INT NOT NULL AUTO_INCREMENT,
  `lessson` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lesson`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz-3`.`themes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-3`.`themes` (
  `id_themes` INT NOT NULL AUTO_INCREMENT,
  `theme_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_themes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz-3`.`lesson_themes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-3`.`lesson_themes` (
  `id_lesson_themes` INT NOT NULL AUTO_INCREMENT,
  `lessson_id` INT NOT NULL,
  `theme_id` INT NOT NULL,
  `time_start` DATE NOT NULL,
  `time_finish` DATE NOT NULL,
  PRIMARY KEY (`id_lesson_themes`),
  INDEX `fk_theme_idx` (`theme_id` ASC) VISIBLE,
  INDEX `fk_lesson_idx` (`lessson_id` ASC) VISIBLE,
  CONSTRAINT `fk_theme`
    FOREIGN KEY (`theme_id`)
    REFERENCES `dz-3`.`themes` (`id_themes`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lesson`
    FOREIGN KEY (`lessson_id`)
    REFERENCES `dz-3`.`lesson` (`id_lesson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz-3`.`attendence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-3`.`attendence` (
  `id_attendence` INT NOT NULL AUTO_INCREMENT,
  `student_id` INT NOT NULL,
  PRIMARY KEY (`id_attendence`),
  INDEX `fk_student_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_student`
    FOREIGN KEY (`student_id`)
    REFERENCES `dz-3`.`student` (`id_student`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz-3`.`group_lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-3`.`group_lesson` (
  `id_group_lesson` INT NOT NULL AUTO_INCREMENT,
  `group_id` INT NOT NULL,
  `lessson_id` INT NOT NULL,
  `time_start` DATE NOT NULL,
  `time_finish` DATE NOT NULL,
  `attendance` INT NOT NULL,
  PRIMARY KEY (`id_group_lesson`),
  INDEX `fk_group_idx` (`group_id` ASC) VISIBLE,
  INDEX `fk_lesson_idx` (`lessson_id` ASC) VISIBLE,
  INDEX `fk_attendence_idx` (`attendance` ASC) VISIBLE,
  CONSTRAINT `fk_group`
    FOREIGN KEY (`group_id`)
    REFERENCES `dz-3`.`group` (`id_group`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_lesson`
    FOREIGN KEY (`lessson_id`)
    REFERENCES `dz-3`.`lesson` (`id_lesson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_attendence`
    FOREIGN KEY (`attendance`)
    REFERENCES `dz-3`.`attendence` (`id_attendence`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
