-- MySQL Script generated by MySQL Workbench
-- жм 21 янв 2022 18:14:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dz-1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dz-1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dz-1` DEFAULT CHARACTER SET utf8 ;
USE `dz-1` ;

-- -----------------------------------------------------
-- Table `dz-1`.`writer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-1`.`writer` (
  `id_writer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `surname` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`id_writer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz-1`.`composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-1`.`composition` (
  `id_composition` INT NOT NULL AUTO_INCREMENT,
  `name_composition` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  `type` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`id_composition`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dz-1`.`writer_composition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-1`.`writer_composition` (
  `id_writer_composition` INT NOT NULL AUTO_INCREMENT,
  `writer_id` INT NOT NULL,
  `composition_id` INT NOT NULL,
  PRIMARY KEY (`id_writer_composition`),
  INDEX `fk_writer_idx` (`writer_id` ASC) VISIBLE,
  INDEX `fk_composition_idx` (`composition_id` ASC) VISIBLE,
  CONSTRAINT `fk_writer`
    FOREIGN KEY (`writer_id`)
    REFERENCES `dz-1`.`writer` (`id_writer`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_composition`
    FOREIGN KEY (`composition_id`)
    REFERENCES `dz-1`.`composition` (`id_composition`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dz-1`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-1`.`genre` (
  `id_genre` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`id_genre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dz-1`.`subgenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-1`.`subgenre` (
  `id_subgenre` INT NOT NULL AUTO_INCREMENT,
  `sub_genre` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_general_ci' NOT NULL,
  PRIMARY KEY (`id_subgenre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dz-1`.`genre_subgenre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-1`.`genre_subgenre` (
  `id_genre_subgenre` INT NOT NULL AUTO_INCREMENT,
  `genre_id` INT NOT NULL,
  `subgenre_id` INT NOT NULL,
  PRIMARY KEY (`id_genre_subgenre`),
  INDEX `fk_genre_idx` (`genre_id` ASC) VISIBLE,
  INDEX `fk_subgenre_idx` (`subgenre_id` ASC) VISIBLE,
  CONSTRAINT `fk_genre`
    FOREIGN KEY (`genre_id`)
    REFERENCES `dz-1`.`genre` (`id_genre`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_subgenre`
    FOREIGN KEY (`subgenre_id`)
    REFERENCES `dz-1`.`subgenre` (`id_subgenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dz-1`.`composition_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz-1`.`composition_genre` (
  `id_composition_genre` INT NOT NULL AUTO_INCREMENT,
  `composition_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`id_composition_genre`),
  INDEX `fk_composition_idx` (`composition_id` ASC) VISIBLE,
  INDEX `fk_genre_idx` (`genre_id` ASC) VISIBLE,
  CONSTRAINT `fk_composition`
    FOREIGN KEY (`composition_id`)
    REFERENCES `dz-1`.`composition` (`id_composition`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_genre`
    FOREIGN KEY (`genre_id`)
    REFERENCES `dz-1`.`genre` (`id_genre`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
